LogConf:
  FileName: "logs/app.log"       # 日志文件路径
  MaxSize: 100                  # 单个日志文件最大尺寸，单位MB
  MaxBackups: 7                # 保留的旧日志文件数量
  MaxAge: 30                   # 日志文件最大保存天数
  Compress: true               # 是否压缩旧日志文件
  Level: "info"               # 日志级别，debug模式
  PrintToConsole: true         # 是否打印到控制台（彩色输出）

AiConf:
  model: llama3.3-70b-instruct
  method: POST
  url: https://api.deepseek.com/chat/completions
#  url: "http://v2.open.venus.oa.com/llmproxy/chat/completions"
  headers:
    Content-Type: application/json
    Authorization: Bearer %s # 将会从env 获取，不能删除这个占位符

  body: > # open ai 通用
    {
      "model": "llama3.3-70b-instruct",
      "messages": [
  
      ],
      "stream": false
    }
