method: POST
url: https://api.deepseek.com/chat/completions
headers:
  Content-Type: application/json
  Authorization: Bearer {{ai_sk}} # 将会从env 获取

body: >
  {
    "model": "deepseek-chat",
    "messages": [
      {"role": "system", "content": "%s"},
      {"role": "user", "content": "%s"} 
    ],
    "stream": false
  }
