method: POST
url: https://api.deepseek.com/chat/completions
headers:
  Content-Type: application/json
  Authorization: Bearer {{env.api_sk}} # 将会从env 获取

body: >
  {
    "model": "deepseek-chat",
    "messages": [
      {"role": "system", "content": "{{system}}"},
      {"role": "user", "content": "{{msg}}"} 
    ],
    "stream": false
  }
  